server:
  httpPort: 80
  httpsPort: 443
  host: '0.0.0.0'
  jwtKey: 'ca0f180dec4c5243012520f01e4ae93f95d41cfd'
  jwtKeyTimeout: '240h'
  cert:
    private: '/etc/ssl/certs/dashabi.key'
    public: '/etc/ssl/certs/dashabi.pem'
option:
  showIP: true
database:
  sqlite:
    path: 'data/users.db'
  redis:
    url: ''
