server:
  httpPort: 80
  httpsPort: 443
  host: '0.0.0.0'
  jwtKey: 'ca0f180dec4c5243012520f01e4ae93f95d41cfd'
  jwtKeyTimeout: '240h'
  cert:
    private: '/etc/ssl/certs/dashabi.key'
    public: '/etc/ssl/certs/dashabi.pem'
  mail:
    smtpUser:
      user: 'serverbread'
      pass: 'RZTJLNZSAPOQKGWQ'
    smtpServer:
      host: 'smtp.163.com'
      port: 465
      secure: true

option:
  showIP: true

database:
  sqlite:
    userDatabase: 'data/users.db'
    registerDatabase: 'data/register.db'
  redis:
    url: ''
