server:
  httpPort: 80
  httpsPort: 443
  host: '0.0.0.0'
  jwtKey: '114514'
  cert:
    private: '/etc/ssl/certs/dashabi.key'
    public: '/etc/ssl/certs/dashabi.pem'
database:
  sqlite:
    path: 'data/users.db'
  redis:
    url: ''
