server:
  httpPort: 80
  httpsPort: 443
  host: '0.0.0.0'
  jwtKey: ''
  jwtKeyTimeout: '240h'
  cert:
    private: '/etc/ssl/certs/dashabi.key'
    public: '/etc/ssl/certs/dashabi.pem'
  mail:
    smtpUser:
      user: ''
      pass: ''
    smtpServer:
      host: ''
      port: 465
      secure: true

option:
  showIP: true

database:
  sqlite:
    userDatabase: 'data/users.db'
    registerDatabase: 'data/register.db'
  redis:
    url: ''
