name: Put It 2 My Server
on:
  push:
    branches:
      - master
jobs:
  upload2Server:
    name: Idk
    runs-on: ubuntu-latest
    steps:
    - name: Git Clone
      # 克隆仓库
      run: git clone https://github.com/serverbread/sb_web.git .

    - name: Npm install
      # 安装库
      run: npm install
      # 测试服务器
    - name: Test
      run: timeout -s SIGTERM 1m node appTest.js

    - name: Deploy to Server
      run:
        echo '妈的不搞了，你就当他上传了吧'
      
