name: Put It 2 My Server
on:
  push:
    branches:
      - master
jobs:
  upload2Server:
    name: Upload 2 Server
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: git clone https://github.com/serverbread/sb_web.git
  
    - name: ShowPWD
      run: pwd

    - name: Build
      run: cd sb_web && npm install && npm run build

    - name: Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.MY_SERVER }}
        ARGS: "-avz --delete"
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}
      run:
        echo '114514'
      
